name: Test

on: [push]
jobs:
  test:

    name: Test PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4', '8.0', '8.1']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: curl, mbstring, intl, libxml, simplexml
          coverage: xdebug
      - name: Get composer cache directory
        id: composer-cache-dir
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache Composer packages
        id: composer-cache-restore
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          # path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          # key: node-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
          # restore-keys: composer-7.2
      - name: Install dependencies
        run: (test -d vendor && echo vendor directory exists) || composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPUnit
        run: vendor/bin/phpunit --coverage-text --coverage-clover clover.xml
      - name: "[Coveralls] Extract branch name"
        if: matrix.php-versions == '8.0'
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: "[Coveralls] Checkout branch"
        if: matrix.php-versions == '8.0'
        shell: bash
        run: git fetch && git checkout ${{ steps.extract_branch.outputs.branch }}
      - name: "[Coveralls] Send report"
        if: matrix.php-versions == '8.0'
        run: vendor/bin/php-coveralls -v -x clover.xml -o coveralls-upload.json
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}